exp_dir: /datasets/work/hb-mlaifsp-mm/work/experiments
dataset_dir: /datasets/work/hb-mlaifsp-mm/work/datasets
ckpt_zoo_dir: /datasets/work/hb-mlaifsp-mm/work/checkpoints

devices: 1
num_workers: 7
memory: '64GB'

module: modules.lightning_modules.no_ca_scst
definition: SCSTNoCrossAttentionBERTScore

warm_start_ckpt_path: /datasets/work/hb-mlaifsp-mm/work/experiments/imageclefmed_caption_2023/002_no_ca/trial_0/epoch=10-val_bertscore_f1=0.618808.ckpt

test_ckpt_name: aehrc/medicap

mbatch_size: 1
lr: 5e-6
val_check_interval: 0.1

max_epochs: 3
accumulated_mbatch_size: 32
every_n_epochs: 1
monitor: 'val_bertscore_f1'
monitor_mode: 'max'
precision: 16
deterministic: False
decoder_max_len: 256
num_test_beams: 4
enable_progress_bar: True
weights_summary: 'full'
